name: After master

on:
  workflow_run:
    workflows: [Publish npm pacakge from master branch, version bump]
    types: [completed]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -al ./.github/workflows
      
      - uses: actions/checkout@v3
        with:
          ref: production
      
      - run: |
          ls -al ./.github/workflows
      
      - uses: actions/checkout@v3
        with:
          ref: master
      
      - run: |
          ls -al ./.github/workflows


    
