name: After production

on:
  repository_dispatch:
    types: [trigger-afterProduction-workflow]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.ref }}


    
