name: Auto Label PR

on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - release/*
      - hotfix/*

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check target branch
        id: target_branch
        run: |
          targetBranch=${{ github.event.pull_request.base.ref }}
          echo "target-branch=$targetBranch" >> $GITHUB_OUTPUT
          echo "target-branch: $targetBranch"
      
      - name: Create label if not exists
        uses: actions/github-script@v6
        with:
          script: |
            const label = '${{ steps.target_branch.outputs.target-branch }}';
            const response = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const labelExists = response.data.some(l => l.name === label);

            if (labelExists) {
              console.log('Label exists:', label);
              return;
            }

            console.log('Label not exist: ', label);

            const color = '#0052CC';
            if (label.includes('hotfix')) {
              const color = '#B60205';
            }

            await github.rest.issues.createLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: `Target branch is $label`,
              name: label,
              color: color
            });

      - name: Add label to pull request
        uses: actions/github-script@v6
        with:
          script: |
            const label = '${{ steps.target_branch.outputs.target-branch }}';

            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label],
            });
