name: Publish npm pacakge
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@allenyummy'
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
      - name: patch version is changed
        if: steps.check.outputs.changed == 'true' && steps.check.outputs.type == 'patch'
        run: |          
          git reset --hard ${{ steps.check.outputs.commit }}
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')

          echo "Version change found in commit ${{ steps.check.outputs.commit }}"
          echo "Old version: $PACKAGE_VERSION"
          echo "New version: ${{ steps.check.outputs.version }}"
          echo "Change type: ${{ steps.check.outputs.type }}"


      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}