name: Pull Request to master

on:
  pull_request:
      branches:
        - master


jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Run script
        run: |
          echo ${{ github.head_ref }}
          cat ./src/src.ts
      
      - name: Print labels
        run: |
          echo "Label:"
          for label in "${{ github.event.pull_request.labels.*.name }}"; do
              echo "- $label"
          done
      
      - name: Print target branch
        run: |
          echo ${{ github.event.pull_request.base.ref }}