name: Pull Request to master

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'
      - '!package.json'
      - '!package-lock.json'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Run script
        run: |
          echo ${{ github.ref }}
          cat ./src/src.ts
      
      - name: Print paths
        run: |
          echo "Paths that triggered the workflow:"
          echo "${{ github.event.commits.author }}"
      
      # - name: Print labels
      #   run: |
      #     echo "Label:"
      #     for label in "${{ github.event.pull_request.labels }}"; do
      #         echo "- $label"
      #     done
      
      # - name: Print target branch
      #   run: |
      #     echo ${{ github.event.pull_request.base.ref }}
      
      # - name: Print changed files
      #   run: |
      #     echo "Changed files:"
      #     echo ${{ github.event.commits.added }}
      #     echo ${{ github.event.commits.modified }}
      #     echo ${{ github.event.commits.removed }}

      #     # for file in "${{ github.event.head_commit.added }} "; do
      #     #   if [[ $file == src/* ]]; then
      #     #     echo "- $file"
      #     #   fi
      #     # done
