name: Pull Request to master

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'         ## packages/*/src
      - '!package.json'
      - '!package-lock.json'

concurrency:
  group: ci-${{ github.ref }}

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" 
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@allenyummy'
      
      - name: install python3
        run: sudo apt-get install -y python3
      
      - name: Run script
        run: |
          echo ${{ github.ref }}
          cat ./src/src.ts
          # newVersion=$(npm version prerelease --preid master --no-git-tag-version)
          # git status
          # git commit -am "chore(fe/abc): bump version to $newVersion"
      
      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Check outputs
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   run: |
      #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
      #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      #     echo "Pull Request Operation - ${{ steps.cpr.outputs.pull-request-operation }}"

      # - name: Enable Automerge
      #   uses: peter-evans/enable-pull-request-automerge@v2
      #   with:
      #     token: ${{ secrets.REVIEW_TOKEN }}
      #     pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      #     merge-method: squash

      # - name: Auto approve
      #   uses: juliangruber/approve-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.REVIEW_TOKEN }}
      #     number: ${{ steps.cpr.outputs.pull-request-number }}
      
      - name: Print changed files
        run: |
          git log --oneline

      - name: Get staged files in two commits
        id: staged-files
        run: |
          filesInOneLine=`python3 << END
          import subprocess

          # Define the two commit hashes you want to compare
          before_commit = "${{ github.event.before }}"
          after_commit = "${{ github.event.after }}"

          # Define the git diff command
          cmd = ["git", "diff", "--name-only", before_commit, after_commit]

          # Run the git diff command and capture its output
          output = subprocess.check_output(cmd)

          # Split the output into a list of file names
          file_list = output.decode().strip().split('\n')

          # Concat array to string
          processStr = '[' + ','.join([f"'{str(file)}'" for file in file_list]) + ']'
          print (processStr)
          END`
          echo "staged_files=$filesInOneLine" >> $GITHUB_OUTPUT

      - name: Print staged files
        run: |
          echo "Staged files:"
          echo "${{ steps.staged-files.outputs.staged_files }}"
      
      # - name: Print labels
      #   run: |
      #     echo "Label:"
      #     for label in "${{ github.event.pull_request.labels }}"; do
      #         echo "- $label"
      #     done
      
      # - name: Print target branch
      #   run: |
      #     echo ${{ github.event.pull_request.base.ref }}
      
      # - name: Print changed files
      #   run: |
      #     echo "Changed files:"
      #     echo ${{ github.event.commits.added }}
      #     echo ${{ github.event.commits.modified }}
      #     echo ${{ github.event.commits.removed }}

      #     # for file in "${{ github.event.head_commit.added }} "; do
      #     #   if [[ $file == src/* ]]; then
      #     #     echo "- $file"
      #     #   fi
      #     # done
